repos:
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.5
    hooks:
      - id: nbqa-black
      - id: nbqa-isort
        args: ["--float-to-top", "--profile=black", "--filter-files"]
      - id: nbqa-flake8
        args: ["--extend-ignore=E501"]
